services:
  - type: web
    name: salesforce-crud-dashboard
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
      - key: SF_LOGIN_URL
        value: https://login.salesforce.com
      - key: SF_CLIENT_ID
        sync: false
      - key: SF_CLIENT_SECRET
        sync: false
      - key: SF_CALLBACK_URL
        sync: false
